site:
  name: Shields Concrete
  site: 'https://shieldsconcrete.ca'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: # Add your Google Search Console verification ID here

# Default SEO metadata
metadata:
  title:
    default: Shields Concrete - Professional Concrete Services in Windsor
    template: '%s | Shields Concrete Windsor'
  description: "Professional concrete services in Windsor, Ontario. Driveways, sidewalks, foundations, and more. Quality workmanship, competitive prices, and reliable service for residential and commercial projects."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Shields Concrete
    images:
      - url: '~/assets/images/shields-concrete-hero.jpg'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your Google Analytics 4 ID here (G-XXXXXXXXXX)

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"